### ISSUE TITLE
Result for PSP

### ISSUE THREAD

**Issue by hrshy0629** [pan2013e/DREval#2]
Test results on PSP subtasks in Direct and CoT mode (GPT-3.5).  CoT is not suitable for this task, is it?
<img width="670" alt="Snipaste_2024-11-08_12-33-05" src="https://github.com/user-attachments/assets/8e90fa8b-174e-48b0-9657-63f397a1c2ac">
<img width="627" alt="Snipaste_2024-11-08_12-33-20" src="https://github.com/user-attachments/assets/d15bdfb4-ed1a-425c-9acc-4f35be876c6a">

**Comment by pan2013e** [comment]
Likely, GPT-3.5's CoT generations do not follow the format of the few-shot examples.
In most cases, commenting out the `if` block in `_postprocess` should work.
https://github.com/pan2013e/DREval/blob/2f148b913deb4ae0e0ce41f0245ef35054ede8d6/evaluation.py#L419-L421

**Comment by hrshy0629** [comment]
![image](https://github.com/user-attachments/assets/1e1b9908-1d25-4942-988f-0f8a4320dd30)
When I remove the _if_ block, the result is shown in the figure.

**Comment by iCSawyer** [comment]
We did not run experiments for GPT-3.5 with CoT in our paper. 

Under CoT settings, we set manual rules to extract the results from the answer of the model. If the model do not strictly follow our instructions (for some reason like a high temperature), we cannot extract it even though the model gives the right answer. I suggest you can manually check the generation results of the model to find whether the model predicts right but the extraction fails. PR is welcome!
